# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/henrychang/nfs/code/ppo_libtorch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/henrychang/nfs/code/ppo_libtorch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henrychang/nfs/code/ppo_libtorch/CMakeFiles /home/henrychang/nfs/code/ppo_libtorch/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henrychang/nfs/code/ppo_libtorch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_ppo

# Build rule for target.
test_ppo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ppo
.PHONY : test_ppo

# fast build rule for target.
test_ppo/fast:
	$(MAKE) -f CMakeFiles/test_ppo.dir/build.make CMakeFiles/test_ppo.dir/build
.PHONY : test_ppo/fast

#=============================================================================
# Target rules for targets named train_ppo

# Build rule for target.
train_ppo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 train_ppo
.PHONY : train_ppo

# fast build rule for target.
train_ppo/fast:
	$(MAKE) -f CMakeFiles/train_ppo.dir/build.make CMakeFiles/train_ppo.dir/build
.PHONY : train_ppo/fast

TestPPO.o: TestPPO.cpp.o

.PHONY : TestPPO.o

# target to build an object file
TestPPO.cpp.o:
	$(MAKE) -f CMakeFiles/test_ppo.dir/build.make CMakeFiles/test_ppo.dir/TestPPO.cpp.o
.PHONY : TestPPO.cpp.o

TestPPO.i: TestPPO.cpp.i

.PHONY : TestPPO.i

# target to preprocess a source file
TestPPO.cpp.i:
	$(MAKE) -f CMakeFiles/test_ppo.dir/build.make CMakeFiles/test_ppo.dir/TestPPO.cpp.i
.PHONY : TestPPO.cpp.i

TestPPO.s: TestPPO.cpp.s

.PHONY : TestPPO.s

# target to generate assembly for a file
TestPPO.cpp.s:
	$(MAKE) -f CMakeFiles/test_ppo.dir/build.make CMakeFiles/test_ppo.dir/TestPPO.cpp.s
.PHONY : TestPPO.cpp.s

TrainPPO.o: TrainPPO.cpp.o

.PHONY : TrainPPO.o

# target to build an object file
TrainPPO.cpp.o:
	$(MAKE) -f CMakeFiles/train_ppo.dir/build.make CMakeFiles/train_ppo.dir/TrainPPO.cpp.o
.PHONY : TrainPPO.cpp.o

TrainPPO.i: TrainPPO.cpp.i

.PHONY : TrainPPO.i

# target to preprocess a source file
TrainPPO.cpp.i:
	$(MAKE) -f CMakeFiles/train_ppo.dir/build.make CMakeFiles/train_ppo.dir/TrainPPO.cpp.i
.PHONY : TrainPPO.cpp.i

TrainPPO.s: TrainPPO.cpp.s

.PHONY : TrainPPO.s

# target to generate assembly for a file
TrainPPO.cpp.s:
	$(MAKE) -f CMakeFiles/train_ppo.dir/build.make CMakeFiles/train_ppo.dir/TrainPPO.cpp.s
.PHONY : TrainPPO.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_ppo"
	@echo "... train_ppo"
	@echo "... TestPPO.o"
	@echo "... TestPPO.i"
	@echo "... TestPPO.s"
	@echo "... TrainPPO.o"
	@echo "... TrainPPO.i"
	@echo "... TrainPPO.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

